- hosts: terraform-ansible
  tasks:
  - name: Instalando erlang e elixir
    apt:
      pkg:
      - erlang
      - elixir
      update_cache: yes
    become: yes
  - name: install build-essential
    apt:
      pkg: build-essential
      update_cache: yes
    become: yes
  - name: Install Hex
    command: mix local.hex --force
    changed_when: >
      "Will always run, don't show that it changed" == 1
